### ISSUE TITLE
Feature request - how to update video metadata

### ISSUE THREAD

**Issue by lorenrisker** [BrightcoveLearning/dynamic-ingest-code-samples#4]
In the documentation, all of the examples for updating metadata or adding captions is in Javascript. Are there any examples written for Python? I am mainly interested in bulk adding of captions and would like to incorporate it into the code I have written based on these samples.

**Comment by rcrooks** [comment]
Hi @lorenrisker we do have this sample Python code: https://apis.support.brightcove.com/dynamic-ingest/code-samples/dynamic-ingest-api-sample-python-code.html 
All Dynamic Ingest requests are the same except for the request body (makes no difference if it's an original ingest or an update). So all you should need to do is modify the `data` part. 

Hope that helps.

**Comment by lorenrisker** [comment]
Thank you, that helps. I think where it gets stuck is while I am able to upload the text tracks, I'm can't figure out how to go back and add it to the videoID.

My current app flow, based on the example you linked:
-create_video (return videoID)
-upload video to s3 (return upload_urls_response as json)
-submit_pbi (this results in the video ingesting as expected)
-upload captions to s3 (return upload_urls_resoonse as json)
-submit_pbi again. (this is where I am missing something)

Once I upload the captions to s3, how do I associate them with the videoID?

**Comment by rcrooks** [comment]
So you don't actually want to upload them to Brightcove? You want them to be used as remote assets from your S3? If that's correct, it's a different API: https://apis.support.brightcove.com/cms/references/reference.html#operation/UpdateVideo

let me know if I'm not understanding what you want to do.

**Comment by lorenrisker** [comment]
I didn't realize I can upload the captions directly to Brightcove. I thought I had to pull them from a server, so I was using S3 just as I did for the video ingest. I appreciate your help - I think I need to revisit how I am approaching this problem.

**Comment by lorenrisker** [comment]
I'm still stumped. I'm using a sample VTT that is publicly available and it returns a 404: Resource Not Found. Are you seeing anything obvious that I am doing wrong?

```
def add_captions_request(pub_id, video_id, upload_urls_response):
    url = ("https://ingest.api.brightcove.com/v1/accounts/{pubid}/videos/{videoid}/ingest-requests").format(pubid=pub_id, videoid=video_id)
    data = '''{
             "master": {
                 "url": "''' + upload_urls_response['api_request_url'] + '''"
             },
             "capture-images": true,
             "text_tracks": [
               {
                 "url": "https://gist.githubusercontent.com/samdutton/ca37f3adaf4e23679957b8083e061177/raw/e19399fbccbc069a2af4266e5120ae6bad62699a/sample.vtt",
                 "srclang": "en",
                 "kind" "captions",
                 "label": "English",
                 "default": true
               }
             ]

             }'''

    r = requests.patch(url, headers=get_authorization_headers(), data=data)
    print(r.json())
    return r.json()
```

**Comment by rcrooks** [comment]
hmmm...not sure why you would get a 404, but that's not related to the text tracks. Are you sure the pub_id and video_id are valid?

**Comment by lorenrisker** [comment]
Thank you! The issue was not with the pub_id or the video_id, but I was using the wrong URL. This worked:

`def add_captions_request(pub_id, video_id, upload_urls_response):
    url = ("https://cms.api.brightcove.com/v1/accounts/{pubid}/videos/{videoid}/").format(pubid=pub_id, videoid=video_id)
    data = '''{
               "long_description": "Herring Gull near Fort Point Channel in Boston, MA, USA. 2019-04-25.",
               "name": "Great Success",
                "text_tracks": [
                               {
                               "default": false,
                               "kind": "captions",
                               "label": "English",
                               "mime_type": null,
                               "src": "http://learning-services-media.brightcove.com/captions/bc_smart_es.vtt",
                               "srclang": "en"
                               }
                               ]
               }'''

     r = requests.patch(url, headers=get_authorization_headers(), data=data)
    print(r)
    return r.json()
`

**Comment by rcrooks** [comment]
Great! Glad you got it working!

**Comment by lorenrisker** [comment]
Actually - still stuck. I can update the video with a caption file, but the actual caption does not work. After I upload the captions to S3, I get a signed_url that looks something like this:

`https://ingestion-upload-production.s3.amazonaws.com/6083430690001/6223282640001/5648d29a-e9ef-43f9-b8b8-4293a2f772b5/%2FUsers/username/Movies/999_01_test1_en.vtt?AWSAccessKeyId=xxxxxxxxxxxxxxxxxxxxx&Expires=1610827336&Signature=xxxxxxxxxxxxxxxxxxxxxxxxxx`

That gives me an error:
<Response [422]>
[{'error_code': 'VALIDATION_ERROR', 'message': 'text_tracks.src: TOO_LONG'}]

Am I using the wrong string for the url?

**Comment by rcrooks** [comment]
ah, I'm not sure that we can ingest from a gist raw file. I don't know that we can't, but I've never come across it. I can check if you like. I think you mentioned that you had these in an S3 bucket - if so, that's something we definitely support. If the bucket objects are public, you'd need to create a bucket access policy to allow our ingest system to read the objects: see https://apis.support.brightcove.com/dynamic-ingest/general/using-dynamic-ingest-s3.html

**Comment by lorenrisker** [comment]
I think the primary issues here is I have no idea what I'm doing. But to answer the question directly, I'm trying to ingest the video and caption file to the same place, the S3 bucket provided by Brightcove. The video file uploads and works fine, but the captions file doesn't. I upload the video file with:

```
def get_upload_location_and_upload_video(account_id, video_id, source_filename):
    # Perform an authorized request to obtain a file upload location
    url = ("https://cms.api.brightcove.com/v1/accounts/{pubid}/videos/{videoid}/upload-urls/{sourcefilename}").format(pubid=account_id, videoid=video_id, sourcefilename=source_filename)
    r = requests.get(url, headers=get_authorization_headers())
    upload_urls_response = r.json()

    # Upload the contents of our local file to the location provided us
    # This example uses the boto3 library to perform a multipart upload
    # This is the recommended method for uploading large source files
    s3 = boto3.resource('s3',
        aws_access_key_id=upload_urls_response['access_key_id'],
        aws_secret_access_key=upload_urls_response['secret_access_key'],
        aws_session_token=upload_urls_response['session_token'])
    logging.debug("187")
    s3.Object(upload_urls_response['bucket'], upload_urls_response['object_key']).upload_file(source_filename)
    return upload_urls_response
```

and then I add the video file with:


```
def di_request(pub_id, video_id, upload_urls_response):
    url = ("https://ingest.api.brightcove.com/v1/accounts/{pubid}/videos/{videoid}/ingest-requests").format(pubid=pub_id, videoid=video_id)
    data = '''{"master": { "url": "''' + upload_urls_response['api_request_url'] + '''" }}'''
    r = requests.post(url, headers=get_authorization_headers(), data=data)
    return r.json()
```

That part works fine. Now I try to upload captions with:

```
def get_upload_location_and_upload_caption(pub_id, video_id, source_filename):
    # Perform an authorized request to obtain a file upload location
    url = ("https://cms.api.brightcove.com/v1/accounts/{pubid}/videos/{videoid}/upload-urls/{sourcefilename}").format(pubid=pub_id, videoid=video_id, sourcefilename=source_filename)
    r = requests.get(url, headers=get_authorization_headers())
    upload_urls_response = r.json()
    with open("/Users/username/Movies/999_01_test1_en.vtt", 'rb') as fh:
        s = requests.put(upload_urls_response['signed_url'], data=fh.read())\
    return upload_urls_response
```

r returns 200, so then I try to add the captions file with:

```
def add_captions_request(pub_id, video_id, upload_urls_response):
    #url = ("https://ingest.api.brightcove.com/v1/accounts/{pubid}/videos/{videoid}/ingest-requests").format(pubid=pub_id, videoid=video_id)
    url = ("https://cms.api.brightcove.com/v1/accounts/{pubid}/videos/{videoid}/").format(pubid=pub_id, videoid=video_id)
    data = '''{
               "long_description": "Attempting to update captions. Text tracks are successfully added as metadata, but source text cannot be loaded",
               "name": "Mild Success",
                "text_tracks": [
                               {
                               "default": false,
                               "kind": "captions",
                               "label": "English",
                               "mime_type": null,
                               "src": "''' + upload_urls_response['api_request_url'] + '''",
                               "srclang": "en"
                               }
                               ]
           }'''
    r = requests.patch(url, headers=get_authorization_headers(), data=data)
    return r.json()
```

My understanding is that I shouldn't need separate functions, but if I use the https://ingest.api.brightcove.com url when adding the captions, I get a 404. I separated this into 2 functions just until I can get it working.

**Comment by lorenrisker** [comment]
Ok finally got it to work. I still think a sample code would be very useful. I uploaded the video and captions in two steps, then modified the di_request to accept both urls. Of course it seems so simple now but took me awhile to get there. 

```
def create_video_entry(d, secrets):
    pub_id = secrets["pub_id"]
    url = ("https://cms.api.brightcove.com/v1/accounts/{pubid}/videos/").format(pubid=pub_id)
    r = requests.post(url, headers=get_authorization_headers(), data=d)
    return r.json()

def get_upload_location_and_upload_video(pub_id, video_id, source_filename):

    # Perform an authorized request to obtain a file upload location
    url = ("https://cms.api.brightcove.com/v1/accounts/{pubid}/videos/{videoid}/upload-urls/{sourcefilename}").format(pubid=pub_id, videoid=video_id, sourcefilename=source_filename)
    r = requests.get(url, headers=get_authorization_headers())
    upload_urls_response = r.json()

    # Upload the contents of our local file to the location provided us
    # This example uses the boto3 library to perform a multipart upload
    # This is the recommended method for uploading large source files
    s3 = boto3.resource('s3',
        aws_access_key_id=upload_urls_response['access_key_id'],
        aws_secret_access_key=upload_urls_response['secret_access_key'],
        aws_session_token=upload_urls_response['session_token'])
    logging.debug("187")
    s3.Object(upload_urls_response['bucket'], upload_urls_response['object_key']).upload_file(source_filename)

    return upload_urls_response

def di_request(pub_id, video_id, upload_urls_response, cap_urls_response):
    
    url = ("https://ingest.api.brightcove.com/v1/accounts/{pubid}/videos/{videoid}/ingest-requests").format(pubid=pub_id, videoid=video_id)
    data = '''{
               "master": {
                   "url": "''' + upload_urls_response['api_request_url'] + '''"
                   },
                   "text_tracks": [{
                       "url": "''' + cap_urls_response['api_request_url'] + '''",
                       "srclang": "en",
                       "kind": "captions",
                       "label": "English",
                       "default": true
                  }]

            }'''
    r = requests.post(url, headers=get_authorization_headers(), data=data)
    return r.json()

# upload metadata and create video in Brightcove
 video_json = create_video_entry(videopath), secrets)

 # upload video to brightcove
 upload_urls = get_upload_location_and_upload_video(secrets["pub_id"], video_json['id'], videoOBJ.path(v))

 # upload captions (and eventually thumbnails)
 cap_urls = get_upload_location_and_upload_video(secrets["pub_id"], video_json['id'], captionspath)

 # add files to brightcove video id
 print(di_request(secrets["pub_id"], video_json['id'], upload_urls, cap_urls))

```
